services:
  cloudflare-ip-allowlist-updater:
    image: ghcr.io/jmengit/cloudflare-ip-allowlist-updater:latest
    container_name: cloudflare-ip-allowlist-updater
    restart: unless-stopped
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN:-replace-me}
      CF_ACCOUNT_ID: ${CF_ACCOUNT_ID:-replace-me}
      CF_POLICY_ID: ${CF_POLICY_ID:-replace-me}
      IP_LOOKUP_ENABLED: ${IP_LOOKUP_ENABLED:-true}
      IP_RANGE: ${IP_RANGE:-}
      IP_FROM_DNS: ${IP_FROM_DNS:-}
      UPDATE_INTERVAL_MINUTES: ${UPDATE_INTERVAL_MINUTES:-15}
      POLICY_REPLACE_ALL: ${POLICY_REPLACE_ALL:-false}
      DRY_RUN: ${DRY_RUN:-false}
      DISABLED: ${DISABLED:-true}
      ONCE: ${ONCE:-false}
